spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
          import_files: classpath:db/data.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        connection:
          charset: utf-8
          characterEncoding: utf-8
          useUnicode: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true